#!/bin/sh
ROOT_DEV=$(mount | grep 'on / ' | awk '{print $1}')
DISK="/dev/$(echo $ROOT_DEV | sed 's/[0-9]*$//')"
parted $DISK resizepart 2 100%
sleep 2
resize2fs $ROOT_DEV
rm -f /etc/uci-defaults/99-expand-rootfs
